package renatohack.minhascompras.Model.GoogleAPI.Classes

data class NextPage (

	val title : String,
	val totalResults : String,
	val searchTerms : String,
	val count : String,
	val startIndex : String,
	val startPage : String,
	val language : String,
	val inputEncoding : String,
	val outputEncoding : String,
	val safe : String,
	val cx : String,
	val sort : String,
	val filter : String,
	val gl : String,
	val cr : String,
	val googleHost : String,
	val disableCnTwTranslation : String,
	val hq : String,
	val hl : String,
	val siteSearch : String,
	val siteSearchFilter : String,
	val exactTerms : String,
	val excludeTerms : String,
	val linkSite : String,
	val orTerms : String,
	val relatedSite : String,
	val dateRestrict : String,
	val lowRange : String,
	val highRange : String,
	val fileType : String,
	val rights : String,
	val searchType : String,
	val imgSize : String,
	val imgType : String,
	val imgColorType : String,
	val imgDominantColor : String
)